In [1]:
# We will do the imports required for this notebook here
%load_ext autoreload
%autoreload 2
# numpy provides import array and linear algebra utilities
import numpy as np

# the robotics toolbox provides robotics specific functionality
import roboticstoolbox as rtb

# spatial math provides objects for representing transformations
import spatialmath as sm

# swift is a lightweight browser-based simulator which comes eith the toolbox
from swift import Swift

# spatialgeometry is a utility package for dealing with geometric objects
import spatialgeometry as sg

# import urchin to read urdf files
from urchin import URDF

# this package provides several solvers for solving quadratic programmes
import qpsolvers as qp 

# modern robotics code library accompanying 
# Modern Robotics: Mechanics, Planning, and Control (Kevin Lynch and Frank Park)
import modern_robotics as mr

# the os package provides utilities for interacting with the operating system
import os

# import config 
from config.config import * 
from models.panda_model import *

import pytransform3d as pt3d
from pytransform3d import(
    transformations as pt,
    rotations as pr,
    trajectories as ptr
)

In [42]:
def init_env():
    # Make the environment
    env = Swift()
    env.launch(realtime=True, browser="notebook")
    
    # import robot
    panda_virtual = create_virtual_panda()
    # set the robot config to ready position
    panda_virtual.q = panda_virtual.qr
    # open the fingers
    panda_virtual.grippers[0].q = [0.035, 0.035]
    
    # create object to grasp
    box = sg.Cuboid(scale=[0.15, 0.07, 0.2],
                    color='pink')
    box.T = sm.SE3(0.7, 0, 0.1)
    box.set_alpha(0.6)
    

    # Set a desired and effector pose an an offset from the current end-effector pose
    bTe = sm.SE3(-box.scale[0]/2 + 0.01, 0, 0) * sm.SE3.Rx(np.pi/2)
    Tep = box.T * bTe
    
    
    # end-effector axes
    ee_axes = sg.Axes(0.1)
    ee_axes.T = panda_virtual.fkine(panda_virtual.q, end='panda_finger_virtual')

    # goal axes
    goal_axes = sg.Axes(0.15)
    # Set the goal axes to Tep
    goal_axes.T = Tep

    box_axes = sg.Axes(0.1)
    box_axes.T = box.T
    
    # add to environment
    
    env.add(panda_virtual)
    env.add(box)
    env.add(ee_axes)
    env.add(goal_axes)
    env.add(box_axes)
    
    return env, Tep, bTe, panda_virtual, ee_axes, goal_axes, box

env, Tep, bTe, panda_virtual, ee_axes, goal_axes, box = init_env()



In [45]:

grasp_axis = (0, -1, 0)
dq = pt.dual_quaternion_from_screw_parameters(q=(0, 0, 0),
                                         s_axis= grasp_axis,
                                         h=0,
                                         theta=np.pi/3,)
wTslip = pt.transform_from_dual_quaternion(dq)

new_dq = pt.dual_quaternion_from_transform(wTslip)
new_dq, dq

(array([ 0.8660254,  0.       , -0.5      ,  0.       ,  0.       ,
         0.       ,  0.       ,  0.       ]),
 array([ 0.8660254,  0.       , -0.5      ,  0.       , -0.       ,
         0.       ,  0.       ,  0.       ]))

In [44]:
eTb = bTe.inv()
wTb = box.T

wTb

array([[1. , 0. , 0. , 0.7],
       [0. , 1. , 0. , 0. ],
       [0. , 0. , 1. , 0.1],
       [0. , 0. , 0. , 1. ]])